### ISSUE TITLE
icclim consecutive dry days for multidimensional DataArray

### ISSUE THREAD

**Issue by srlightfoote** [Ouranosinc/xclim#194]
* xclim version:0.7-beta
* Python version:3.5.5
* Operating System:windows

### Description

I get an error when using `xclim.icclim.CDD` for multi-dimensional DataArray's (time, lat, lon).  The function only seems to work on 1-D DataArrays (time).  Is this an expected limitation?

### What I Did

```
import xarray as xr
import xclim
xclim.__version__
xr.__version__
dst = xr.open_dataset(filename).load()
dst
<xarray.Dataset>
Dimensions:  (lat: 614, lon: 928, time: 31)
Coordinates:
  * lon      (lon) float64 -125.0 -124.9 -124.8 -124.8 ... -67.16 -67.09 -67.03
  * lat      (lat) float64 14.66 14.72 14.78 14.84 ... 52.78 52.84 52.91 52.97
  * time     (time) datetime64[ns] 2013-12-01 2013-12-02 ... 2013-12-31
Data variables:
    Prec     (time, lat, lon) float32 nan nan nan ... 3.0565994 3.090496
    Tmax     (time, lat, lon) float32 nan nan nan nan ... -26.93 -26.76 -26.98
    Tmin     (time, lat, lon) float32 nan nan nan nan ... -34.95 -34.74 -34.94
    wind     (time, lat, lon) float32 nan nan nan ... 2.6853178 2.6731944
Attributes:
    CDI:                       Climate Data Interface version 1.6.4 (http://c...
    Conventions:               CF-1.4
    history:                   Sat Oct 11 18:46:27 2014: cdo ifthenelse /Volu...
    nco_openmp_thread_number:  1
    NCO:                       4.4.5
    CDO:                       Climate Data Operators version 1.6.4 (http://c...

#%%
xclim.icclim.CDD(dst.Prec.sel(lat=40, lon=-100, method='nearest'))
<xarray.DataArray (time: 1)>
dask.array<shape=(1,), dtype=float64, chunksize=(1,)>
Coordinates:
  * time     (time) datetime64[ns] 2013-01-01
    lon      float64 -99.97
    lat      float64 40.03
#%%
xclim.icclim.CDD(dst.Prec)
TypeError                                 Traceback (most recent call last)
 in ()
      1 #%%
----> 2 xclim.icclim.CDD(dst.Prec)

~\AppData\Roaming\Python\Python35\site-packages\xclim\indices.py in maximum_consecutive_dry_days(pr, thresh, freq)
    307 
    308     group = (pr < thresh).resample(time=freq)
--> 309     return group.apply(rl.longest_run, dim='time')
    310 
    311 

C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\resample.py in apply(self, func, shortcut, args, **kwargs)
    206         """
    207         combined = super(DataArrayResample, self).apply(
--> 208             func, shortcut=shortcut, args=args, **kwargs)
    209 
    210         # If the aggregation function didn't drop the original resampling

C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\groupby.py in apply(self, func, shortcut, args, **kwargs)
    556         applied = (maybe_wrap_array(arr, func(arr, *args, **kwargs))
    557                    for arr in grouped)
--> 558         return self._combine(applied, shortcut=shortcut)
    559 
    560     def _combine(self, applied, shortcut=False):

C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\groupby.py in _combine(self, applied, shortcut)
    560     def _combine(self, applied, shortcut=False):
    561         """Recombine the applied objects like the original."""
--> 562         applied_example, applied = peek_at(applied)
    563         coord, dim, positions = self._infer_concat_args(applied_example)
    564         if shortcut:

C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\utils.py in peek_at(iterable)
    137     """
    138     gen = iter(iterable)
--> 139     peek = next(gen)
    140     return peek, itertools.chain([peek], gen)
    141 

C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\groupby.py in (.0)
    555             grouped = self._iter_grouped()
    556         applied = (maybe_wrap_array(arr, func(arr, *args, **kwargs))
--> 557                    for arr in grouped)
    558         return self._combine(applied, shortcut=shortcut)
    559 

~\AppData\Roaming\Python\Python35\site-packages\xclim\run_length.py in longest_run(da, dim)
     58         """
     59 
---> 60     d = rle(da, dim=dim)
     61     rl_long = d.max(dim=dim)
     62 

~\AppData\Roaming\Python\Python35\site-packages\xclim\run_length.py in rle(da, dim, max_chunk)
     32         if dd != dim:
     33             chunks[dd] = chunksize_ex_dims
---> 34     b = b.chunk(chunks)
     35 
     36     # back fill nans with first position after

C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\dataarray.py in chunk(self, chunks, name_prefix, token, lock)
    812 
    813         ds = self._to_temp_dataset().chunk(chunks, name_prefix=name_prefix,
--> 814                                            token=token, lock=lock)
    815         return self._from_temp_dataset(ds)
    816 

C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\dataset.py in chunk(self, chunks, name_prefix, token, lock)
   1484 
   1485         variables = OrderedDict([(k, maybe_chunk(k, v, chunks))
-> 1486                                  for k, v in self.variables.items()])
   1487         return self._replace(variables)
   1488 

C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\dataset.py in (.0)
   1484 
   1485         variables = OrderedDict([(k, maybe_chunk(k, v, chunks))
-> 1486                                  for k, v in self.variables.items()])
   1487         return self._replace(variables)
   1488 

C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\dataset.py in maybe_chunk(name, var, chunks)
   1479                 token2 = tokenize(name, token if token else var._data)
   1480                 name2 = '%s%s-%s' % (name_prefix, name, token2)
-> 1481                 return var.chunk(chunks, name=name2, lock=lock)
   1482             else:
   1483                 return var

C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\variable.py in chunk(self, chunks, name, lock)
    882         data = self._data
    883         if isinstance(data, da.Array):
--> 884             data = data.rechunk(chunks)
    885         else:
    886             if utils.is_dict_like(chunks):

C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\dask\array\core.py in rechunk(self, chunks, threshold, block_size_limit)
   1767         """ See da.rechunk for docstring """
   1768         from . import rechunk   # avoid circular import
-> 1769         return rechunk(self, chunks, threshold, block_size_limit)
   1770 
   1771     @property

C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\dask\array\rechunk.py in rechunk(x, chunks, threshold, block_size_limit)
    249     if isinstance(chunks, dict):
    250         if not chunks or isinstance(next(iter(chunks.values())), int):
--> 251             chunks = blockshape_dict_to_tuple(x.chunks, chunks)
    252         else:
    253             chunks = blockdims_dict_to_tuple(x.chunks, chunks)

C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\dask\array\rechunk.py in blockshape_dict_to_tuple(old_chunks, d)
    202             v = shape[k]
    203         div, mod = divmod(shape[k], v)
--> 204         new_chunks[k] = (v,) * div + ((mod,) if mod else ())
    205     return tuple(new_chunks)
    206 

TypeError: can't multiply sequence by non-int of type 'numpy.float64'
```

**Comment by huard** [comment]
Hi Stephen, 

It *should* work. The bug you're seeing is probably related to https://github.com/Ouranosinc/xclim/pull/146

Are some of your grid cells entirely filled with NaNs along time ? Filling those NaNs with values that won't interfere with the results might be the quick fix for you while we look for a more satisfying solution.

**Comment by Zeitsperre** [comment]
The current beta on PyPI doesn't integrate the changes from @jwenfai's work. It might be good to tag a new version very soon.

**Comment by slightfoote** [comment]
Thanks for the quick response.  I'm still seeing the issue after apply `fillna(0)` to my data.  Here's an attempt at a fully reproducible example.  Thanks again.

```
Python 3.5.5 |Anaconda, Inc.| (default, Apr  7 2018, 04:52:34) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> import xarray as xr
>>> import xclim
WARNING:py.warnings:C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\options.py:50: FutureWarning: The enable_cftimeindex option is now a no-op and will be removed in a future version of xarray.
  FutureWarning)

>>> xclim.__version__
'0.7-beta'
>>> xr.__version__
'0.12.1'
>>> requests.__version__
'2.18.4'
>>> url = 'https://data.nodc.noaa.gov/nodc/archive/data/0129374/daily/livneh_NAmerExt_15Oct2014.200101.nc'
>>> data = requests.get(url, stream=True)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): data.nodc.noaa.gov
DEBUG:urllib3.connectionpool:https://data.nodc.noaa.gov:443 "GET /nodc/archive/data/0129374/daily/livneh_NAmerExt_15Oct2014.200101.nc HTTP/1.1" 200 282633104
>>> dst = xr.open_dataset(data.content).load()
>>> dst.close()
>>> dst
<xarray.Dataset>
Dimensions:  (lat: 614, lon: 928, time: 31)
Coordinates:
  * lon      (lon) float64 -125.0 -124.9 -124.8 -124.8 ... -67.16 -67.09 -67.03
  * lat      (lat) float64 14.66 14.72 14.78 14.84 ... 52.78 52.84 52.91 52.97
  * time     (time) datetime64[ns] 2001-01-01 2001-01-02 ... 2001-01-31
Data variables:
    Prec     (time, lat, lon) float32 nan nan nan nan nan ... 0.0 0.0 0.0 0.0
    Tmax     (time, lat, lon) float32 nan nan nan nan ... -23.29 -23.13 -23.36
    Tmin     (time, lat, lon) float32 nan nan nan nan ... -33.36 -33.17 -33.39
    wind     (time, lat, lon) float32 nan nan nan ... 2.4911833 2.5031376
Attributes:
    CDI:                       Climate Data Interface version 1.6.4 (http://c...
    Conventions:               CF-1.4
    history:                   Sat Oct 11 13:52:21 2014: cdo ifthenelse /Volu...
    nco_openmp_thread_number:  1
    NCO:                       4.4.5
    CDO:                       Climate Data Operators version 1.6.4 (http://c...
>>> xclim.icclim.CDD(dst.Prec.sel(lat=40, lon=-110, method='nearest'), freq='7D')
<xarray.DataArray (time: 5)>
dask.array<shape=(5,), dtype=float64, chunksize=(1,)>
Coordinates:
  * time     (time) datetime64[ns] 2001-01-01 2001-01-08 ... 2001-01-29
    lon      float64 -110.0
    lat      float64 40.03
>>> dst['Prec'] = dst['Prec'].fillna(0)
>>> dst.Prec.isnull().sum()
<xarray.DataArray 'Prec' ()>
array(0)
>>> xclim.icclim.CDD(dst.Prec, freq='7D')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sligthfoote\AppData\Roaming\Python\Python35\site-packages\xclim\indices.py", line 309, in maximum_consecutive_dry_days
    return group.apply(rl.longest_run, dim='time')
  File "C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\resample.py", line 208, in apply
    func, shortcut=shortcut, args=args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\groupby.py", line 558, in apply
    return self._combine(applied, shortcut=shortcut)
  File "C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\groupby.py", line 562, in _combine
    applied_example, applied = peek_at(applied)
  File "C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\utils.py", line 139, in peek_at
    peek = next(gen)
  File "C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\groupby.py", line 557, in <genexpr>
    for arr in grouped)
  File "C:\Users\sligthfoote\AppData\Roaming\Python\Python35\site-packages\xclim\run_length.py", line 60, in longest_run
    d = rle(da, dim=dim)
  File "C:\Users\sligthfoote\AppData\Roaming\Python\Python35\site-packages\xclim\run_length.py", line 34, in rle
    b = b.chunk(chunks)
  File "C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\dataarray.py", line 814, in chunk
    token=token, lock=lock)
  File "C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\dataset.py", line 1486, in chunk
    for k, v in self.variables.items()])
  File "C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\dataset.py", line 1486, in <listcomp>
    for k, v in self.variables.items()])
  File "C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\dataset.py", line 1481, in maybe_chunk
    return var.chunk(chunks, name=name2, lock=lock)
  File "C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\variable.py", line 884, in chunk
    data = data.rechunk(chunks)
  File "C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\dask\array\core.py", line 1769, in rechunk
    return rechunk(self, chunks, threshold, block_size_limit)
  File "C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\dask\array\rechunk.py", line 251, in rechunk
    chunks = blockshape_dict_to_tuple(x.chunks, chunks)
  File "C:\ProgramData\Anaconda3\envs\pf-ds-35\lib\site-packages\dask\array\rechunk.py", line 204, in blockshape_dict_to_tuple
    new_chunks[k] = (v,) * div + ((mod,) if mod else ())
TypeError: can't multiply sequence by non-int of type 'numpy.float64'
```

**Comment by huard** [comment]
I could not reproduce this issue with the github master, so I assume the issue you're seeing has already been fixed. Note however that we've enforced stricter rules regarding units, so I had to modify the units in place from mm to mm/day to get the example to work.  
```
In [15]: ds = xr.open_dataset('/home/david/Downloads/livneh_NAmerExt_15Oct2014.200101.nc')                                                                                                                  

In [16]: ds.Prec.attrs['units'] = 'mm/day'                                                                                                                                                                  

In [17]: xclim.icclim.CDD(ds.Prec, freq='7D')                                                                                                                                                               
Out[17]: 
<xarray.DataArray (time: 5, lat: 614, lon: 928)>
dask.array<shape=(5, 614, 928), dtype=float64, chunksize=(1, 333, 333)>
Coordinates:
  * time     (time) datetime64[ns] 2001-01-01 2001-01-08 ... 2001-01-29
  * lon      (lon) float64 -125.0 -124.9 -124.8 -124.8 ... -67.16 -67.09 -67.03
  * lat      (lat) float64 14.66 14.72 14.78 14.84 ... 52.78 52.84 52.91 52.97
Attributes:
    units:    days
```
@Zeitsperre  Could you cut a minor release ? 
@slightfoote Thanks for the bug report. Let us know if you encounter other issues or want to comment on the overall design. Note that we're due for some clean-up and refactoring before the 1.0 release, but the `xclim.icclim` interface shouldn't change.

**Comment by Zeitsperre** [comment]
@huard I'll see if I can get a new beta up on PyPI by the end of the week. Let's focus on stability fixes for the next few days until then?

**Comment by slightfoote** [comment]
OK, thanks David.  I still see the bug on my end when cloning and installing the github master but was able to run in a separate linux container. So must be a python environment issue on my end.  Thanks for looking into this.

**Comment by huard** [comment]
Hum, let us know if you have ideas about what could cause this. Could it be different xarray versions ?

**Comment by Zeitsperre** [comment]
@slightfoote if you run the following, does the problem persist?
```
pip install --upgrade xarray
```

**Comment by slightfoote** [comment]
@Zeitsperre , yes.  See below.  I'm sure it's some sort of silly package conflict on my side or perhaps a windows vs. linux issue (the OS I'm using where the function errors is Windows whereas the function does not error when running in a linux docker container).  Thanks for creating such a great library!
```
>>> import xarray as xr
>>> import xclim
WARNING:py.warnings:C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\options.py:50: FutureWarning: The enable_cftimeindex option is now a no-op and will be removed in a future version of xarray.
  FutureWarning)

>>> import requests
>>> url = 'https://data.nodc.noaa.gov/nodc/archive/data/0129374/daily/livneh_NAmerExt_15Oct2014.200101.nc'
>>> data = requests.get(url, stream=True)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): data.nodc.noaa.gov
DEBUG:urllib3.connectionpool:https://data.nodc.noaa.gov:443 "GET /nodc/archive/data/0129374/daily/livneh_NAmerExt_15Oct2014.200101.nc HTTP/1.1" 200 282633104
>>> dst = xr.open_dataset(data.content).load()
>>> dst.Prec.attrs['units']='mm/day'
>>> xclim.icclim.CDD(dst.Prec,freq='7D')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\xclim\indices.py", line 309, in maximum_consecutive_dry_days
    return group.apply(rl.longest_run, dim='time')
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\resample.py", line 208, in apply
    func, shortcut=shortcut, args=args, **kwargs)
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\groupby.py", line 558, in apply
    return self._combine(applied, shortcut=shortcut)
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\groupby.py", line 562, in _combine
    applied_example, applied = peek_at(applied)
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\utils.py", line 139, in peek_at
    peek = next(gen)
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\groupby.py", line 557, in <genexpr>
    for arr in grouped)
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\xclim\run_length.py", line 60, in longest_run
    d = rle(da, dim=dim)
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\xclim\run_length.py", line 34, in rle
    b = b.chunk(chunks)
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\dataarray.py", line 814, in chunk
    token=token, lock=lock)
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\dataset.py", line 1486, in chunk
    for k, v in self.variables.items()])
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\dataset.py", line 1486, in <listcomp>
    for k, v in self.variables.items()])
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\dataset.py", line 1481, in maybe_chunk
    return var.chunk(chunks, name=name2, lock=lock)
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\xarray\core\variable.py", line 884, in chunk
    data = data.rechunk(chunks)
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\dask\array\core.py", line 1769, in rechunk
    return rechunk(self, chunks, threshold, block_size_limit)
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\dask\array\rechunk.py", line 251, in rechunk
    chunks = blockshape_dict_to_tuple(x.chunks, chunks)
  File "C:\Users\sligthfoote\Anaconda3\envs\pf-ds-35\lib\site-packages\dask\array\rechunk.py", line 204, in blockshape_dict_to_tuple
    new_chunks[k] = (v,) * div + ((mod,) if mod else ())
TypeError: 'numpy.float64' object cannot be interpreted as an integer
>>> xr.__version__
'0.12.1'
>>> import pandas as pd
>>> pd.__version__
'0.23.4'
>>> import numpy as np
>>> np.__version__
'1.14.3'
>>>
```
