### ISSUE TITLE
`subset_shape` with large input data

### ISSUE THREAD

**Issue by davidcaron** [Ouranosinc/xclim#403]
* xclim version: 0.15.0
* Python version: 3.8
* Operating System: ubuntu

### Description

Calling the `subset_shape` function on a large input dataset crashes when the dataset doesn't fit in memory. Not with a large polygon subset, but a large source dataset. So I want to subset a small portion of a large file.

### What I Did

I was using xclim through finch, the source data is the daily bccaqv2 datasets. 

### What I Received

```
finch         | INFO:PYWPS:Subsetting file 1 of 48 
finch         | Traceback (most recent call last):
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/pywps/app/Process.py", line 243, in _run_process
finch         |     self.handler(wps_request, wps_response)  # the user must update the wps_response.
finch         |   File "/code/finch/processes/wps_base.py", line 36, in _handler_wrapper
finch         |     return self.wrapped_handler(request, response)
finch         |   File "/code/finch/processes/wps_ensemble_indices_polygon.py", line 74, in _handler
finch         |     return ensemble_common_handler(self, request, response, finch_subset_shape)
finch         |   File "/code/finch/processes/ensemble_utils.py", line 528, in ensemble_common_handler
finch         |     subsetted_files = subset_function(
finch         |   File "/code/finch/processes/subset.py", line 234, in finch_subset_shape
finch         |     process_threaded(_subset, netcdf_inputs)
finch         |   File "/code/finch/processes/utils.py", line 274, in process_threaded
finch         |     outputs = [function(r) for r in inputs]
finch         |   File "/code/finch/processes/utils.py", line 274, in <listcomp>
finch         |     outputs = [function(r) for r in inputs]
finch         |   File "/code/finch/processes/subset.py", line 219, in _subset
finch         |     subsetted = subset_shape(
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xclim/subset.py", line 208, in func_checker
finch         |     final = func(*formatted_args, **kwargs)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xclim/subset.py", line 465, in subset_shape
finch         |     ds_copy = copy.deepcopy(ds)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/copy.py", line 153, in deepcopy
finch         |     y = copier(memo)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/core/dataset.py", line 1181, in __deepcopy__
finch         |     return self.copy(deep=True)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/core/dataset.py", line 1073, in copy
finch         |     variables = {k: v.copy(deep=deep) for k, v in self._variables.items()}
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/core/dataset.py", line 1073, in <dictcomp>
finch         |     variables = {k: v.copy(deep=deep) for k, v in self._variables.items()}
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/core/variable.py", line 885, in copy
finch         |     data = np.array(data)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/core/indexing.py", line 677, in __array__
finch         |     self._ensure_cached()
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/core/indexing.py", line 674, in _ensure_cached
finch         |     self.array = NumpyIndexingAdapter(np.asarray(self.array))
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/numpy/core/_asarray.py", line 85, in asarray
finch         |     return array(a, dtype, copy=False, order=order)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/core/indexing.py", line 653, in __array__
finch         |     return np.asarray(self.array, dtype=dtype)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/numpy/core/_asarray.py", line 85, in asarray
finch         |     return array(a, dtype, copy=False, order=order)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/core/indexing.py", line 557, in __array__
finch         |     return np.asarray(array[self.key], dtype=None)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/numpy/core/_asarray.py", line 85, in asarray
finch         |     return array(a, dtype, copy=False, order=order)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/coding/variables.py", line 72, in __array__
finch         |     return self.func(self.array)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/coding/variables.py", line 218, in _scale_offset_decoding
finch         |     data = np.array(data, dtype=dtype, copy=True)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/coding/variables.py", line 72, in __array__
finch         |     return self.func(self.array)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/coding/variables.py", line 138, in _apply_mask
finch         |     data = np.asarray(data, dtype=dtype)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/numpy/core/_asarray.py", line 85, in asarray
finch         |     return array(a, dtype, copy=False, order=order)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/core/indexing.py", line 557, in __array__
finch         |     return np.asarray(array[self.key], dtype=None)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 72, in __getitem__
finch         |     return indexing.explicit_indexing_adapter(
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/core/indexing.py", line 837, in explicit_indexing_adapter
finch         |     result = raw_indexing_method(raw_key.tuple)
finch         |   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 85, in _getitem
finch         |     array = getitem(original_array, key)
finch         |   File "netCDF4/_netCDF4.pyx", line 4389, in netCDF4._netCDF4.Variable.__getitem__
finch         | MemoryError: Unable to allocate 55.9 GiB for an array with shape (1068, 510, 55115) and data type int16
```

**Comment by tlogan2000** [comment]
Will take a quick look... seems odd

**Comment by davidcaron** [comment]
I'm just guessing, but maybe instead of calling `ds_copy = copy.deepcopy(ds)` trying `ds.copy(deep=True)`?

**Comment by tlogan2000** [comment]
This works for me ... are you chunking the dataset so that dask is used?
memory didn't get over 1GB

```
import xarray as xr
from xclim import subset
from dask.diagnostics import ProgressBar
test_poly = 'small_geojson.json'
url = 'https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/pcic/BCCAQv2_rechunked/tasmin_day_BCCAQv2+ANUSPLIN300_inmcm4_historical+rcp85_r1i1p1_19500101-21001231.nc'
ds = xr.open_dataset(url, chunks=dict(time=100,lat=100,lon=100))
with ProgressBar():
    ds1 = subset.subset_shape(ds, test_poly, buffer=.5)
    ds1.to_netcdf('test_subshp.nc')
ds2 = xr.open_dataset('test_subshp.nc')
ds2.isel(time=10).tasmin.plot()
```
json file : is this one https://github.com/Ouranosinc/xclim/blob/master/tests/testdata/cmip5/small_geojson.json

**Comment by tlogan2000** [comment]
FYI - xclim version on boreas right now is 0.14.0.  Do you know which version is in finch?

**Comment by davidcaron** [comment]
hum... my dataset is probably not chunked, that should help. I'm using xclim 0.15.0.

**Comment by tlogan2000** [comment]
let me know if it works out

**Comment by tlogan2000** [comment]
@Zeitsperre @aulemahal just curious ... does anyone recall why we do the deepcopy() calls at the beginning of  subset_shape

**Comment by aulemahal** [comment]
The copy is because the dataset is modified in-place later. I am not sure about the `deepcopy` though... It does seem overkill, at first sight even `ds.copy()` (without `deep=True`) should suffice.

**Comment by huard** [comment]
Correct me if I'm wrong, but there is no risk of modifying the original data, as long as we don't call to_netcdf on the same path. Everything is in memory.

**Comment by tlogan2000** [comment]
I see a small TODO here ... I think it was possibly the meridian splitting decorator that does something unexpected without the copy.

**Comment by aulemahal** [comment]
Maybe that's something no longer applicable? Because the `wrap_lons_and_split_at_greenwich` is called further down and only modifies poly, not ds.

@huard  But still : doing  `ds['v'] = blabla` would modify the dataset that the user gave in input.

**Comment by huard** [comment]
Yes indeed. Sorry, I misunderstood.

**Comment by davidcaron** [comment]
I'm closing this, chunking the datasets will work.
