### ISSUE TITLE
Random seeded K-Means Reduce Ensemble doctest can sometimes fail

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#871]
* xclim version: 0.30.2-beta
* Python version: 3.7
* Operating System: Linux

### Description

I've seen this happen a few times, but it looks as though the random number generation isn't reproducing the exact same results despite using a random number seed? I'm not sure how that can be happening.

### What I Did

```
$ git push
```

### What I Received

```
=================================== FAILURES ===================================
_____________________ [xdoctest] kmeans_reduce_ensemble:0 ______________________
* REASON: ValueError
DOCTEST DEBUG INFO
  XDoc "/home/runner/work/xclim/xclim/xclim/ensembles/_reduce.py::kmeans_reduce_ensemble:0", line 31 <- wrt doctest
  File "/home/runner/work/xclim/xclim/xclim/ensembles/_reduce.py", line 222, <- wrt source file
DOCTEST PART BREAKDOWN
Passed Parts:
     1 >>> import xclim
     2 >>> from xclim.ensembles import create_ensemble, kmeans_reduce_ensemble
     3 >>> from xclim.indices import hot_spell_frequency
     7 >>> ensTas = create_ensemble(temperature_datasets)
    12 >>> tg = xclim.atmos.tg_mean(tas=ensTas.tas)
    13 >>> his_tg = tg.sel(time=slice('1990','2019')).mean(dim='time')
    14 >>> fut_tg = tg.sel(time=slice('2020','2050')).mean(dim='time')
    15 >>> dtg = fut_tg - his_tg
    19 >>> hs = hot_spell_frequency(tasmax=ensTas.tas, window=2, thresh_tasmax='10 degC')
    20 >>> his_hs = hs.sel(time=slice('1990','2019')).mean(dim='time')
    21 >>> fut_hs = hs.sel(time=slice('2020','2050')).mean(dim='time')
    22 >>> dhs = fut_hs - his_hs
    26 >>> from xarray import concat
    27 >>> crit = concat((dtg, dhs), dim='criteria')
Failed Part:
    31 >>> ids, cluster, fig_data = kmeans_reduce_ensemble(data=crit, method={'rsq_cutoff':0.9}, random_state=42, make_graph=False)
    32 >>> ids, cluster, fig_data = kmeans_reduce_ensemble(data=crit, method={'rsq_optimize':None}, random_state=42, make_graph=True)
DOCTEST TRACEBACK
Traceback (most recent call last):

  File "/home/runner/work/xclim/xclim/.tox/doctests/lib/python3.7/site-packages/xdoctest/doctest_example.py", line 653, in run
    exec(code, test_globals)

  File "<doctest:/home/runner/work/xclim/xclim/xclim/ensembles/_reduce.py::kmeans_reduce_ensemble:0>", line rel: 31, abs: 222, in <module>
    >>> ids, cluster, fig_data = kmeans_reduce_ensemble(data=crit, method={'rsq_cutoff':0.9}, random_state=42, make_graph=False)

  File "/home/runner/work/xclim/xclim/xclim/ensembles/_reduce.py", line 262, in kmeans_reduce_ensemble
    rsq = _calc_rsq(z, method, make_graph, n_sim, random_state, sample_weights)

  File "/home/runner/work/xclim/xclim/xclim/ensembles/_reduce.py", line 337, in _calc_rsq
    kmeans = kmeans.fit(z, sample_weight=sample_weights)

  File "/home/runner/work/xclim/xclim/.tox/doctests/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 1145, in fit
    accept_large_sparse=False,

  File "/home/runner/work/xclim/xclim/.tox/doctests/lib/python3.7/site-packages/sklearn/base.py", line 557, in _validate_data
    X = check_array(X, **check_params)

  File "/home/runner/work/xclim/xclim/.tox/doctests/lib/python3.7/site-packages/sklearn/utils/validation.py", line 792, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")

  File "/home/runner/work/xclim/xclim/.tox/doctests/lib/python3.7/site-packages/sklearn/utils/validation.py", line 116, in _assert_all_finite
    type_err, msg_dtype if msg_dtype is not None else X.dtype

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

DOCTEST REPRODUCTION
CommandLine:
    pytest /home/runner/work/xclim/xclim/xclim/ensembles/_reduce.py::kmeans_reduce_ensemble:0
/home/runner/work/xclim/xclim/xclim/ensembles/_reduce.py:222: ValueError
----------------------------- Captured stdout call -----------------------------
====== <exec> ======
* DOCTEST : /home/runner/work/xclim/xclim/xclim/ensembles/_reduce.py::kmeans_reduce_ensemble:0, line 192 <- wrt source file
=========================== short test summary info ============================
FAILED xclim/testing/tests/ensembles/_reduce.py::kmeans_reduce_ensemble:0
=================== 1 failed, 54 passed, 1 skipped in 28.65s ===================
ERROR: InvocationError for command /home/runner/work/xclim/xclim/.tox/doctests/bin/pytest --rootdir xclim/testing/tests/ --xdoctest xclim --ignore=xclim/testing/tests/ (exited with code 1)
```

**Comment by Zeitsperre** [comment]
See also: https://github.com/Ouranosinc/xclim/runs/3873768072?check_suite_focus=true

**Comment by Zeitsperre** [comment]
Just bugged again, this time when merged to master: https://github.com/Ouranosinc/xclim/runs/4253202184?check_suite_focus=true#step:5:1050

**Comment by Zeitsperre** [comment]
It seems as though this test (in a notebook) is causing intermittent failures on ReadTheDocs now (https://readthedocs.org/projects/xclim/builds/15711114/):

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/nbclient/client.py", line 626, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/nbclient/util.py", line 96, in ensure_async
    result = await obj
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/nbsphinx.py", line 1032, in parse
    rststring, resources = exporter.from_notebook_node(nb, resources)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/nbsphinx.py", line 842, in from_notebook_node
    nb, resources = pp.preprocess(nb, resources)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 84, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 105, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/nbclient/client.py", line 838, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/nbclient/client.py", line 650, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/nbclient/client.py", line 698, in _async_handle_timeout
    "Cell execution timed out", timeout, cell
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 300 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
## UNNESTED results using k-means
for n in np.arange(5, 14, 2):
    ids, cluster, fig_data = ensembles.kmeans_reduce_ensemble(
        crit, method={"n_clusters": n}, random_state=42, make_graph=True
    )
    print(ids)
-------------------


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 344, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 308, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 415, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 436, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 476, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/sphinx/io.py", line 189, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/sphinx/io.py", line 109, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xclim/envs/latest/lib/python3.7/site-packages/nbsphinx.py", line 1043, in parse
    str(e))
nbsphinx.NotebookError: CellTimeoutError in notebooks/ensembles-advanced.ipynb:
A cell timed out while it was being executed, after 300 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
## UNNESTED results using k-means
for n in np.arange(5, 14, 2):
    ids, cluster, fig_data = ensembles.kmeans_reduce_ensemble(
        crit, method={"n_clusters": n}, random_state=42, make_graph=True
    )
    print(ids)
-------------------


Notebook error:
CellTimeoutError in notebooks/ensembles-advanced.ipynb:
A cell timed out while it was being executed, after 300 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
## UNNESTED results using k-means
for n in np.arange(5, 14, 2):
    ids, cluster, fig_data = ensembles.kmeans_reduce_ensemble(
        crit, method={"n_clusters": n}, random_state=42, make_graph=True
    )
    print(ids)
-------------------
```
