### ISSUE TITLE
Using xclim with WRF output

### ISSUE THREAD

**Issue by Murk89** [Ouranosinc/xclim#989]
* xclim version: 0.32.1
* Python version:3.7
* Operating System:Windows

### Description
I want to use some of the climate indices of xclim to analyse output from the Weather Research and Forecast Model (WRF). I tried the cold spell frequency and there is an error as explained below.  Would appreciate any help. 

### What I Did

```
import xclim as xc
import numpy as np
import pandas as pd
import xarray as xr
import h5netcdf
import netCDF4
import time
import tempfile

DS=xr.open_mfdataset("C:\\Users\\Public\\Documents\\Python files for plotting wrfoutput\\*.nc",concat_dim='Time', combine='nested', compat='no_conflicts', preprocess=None, engine=None, data_vars='all', coords='all', parallel=False, join='outer', attrs_file=None,)

DS= DS.rename({'XTIME':'Time'})
DS=DS.assign_coords(Time=pd.to_datetime(DS['Time'].values))


#try xclim index
T2=DS.T2
cs=xc.indicators.atmos.cold_spell_days(T2)


```

### What I Received

```
csd=xc.indicators.atmos.cold_spell_days(T2)
C:\Users\murk_\Documents\New folder\envs\my_xclim\lib\site-packages\xclim\core\cfchecks.py:40: UserWarning: Variable does not have a `cell_methods` attribute.
  getattr(vardata, "cell_methods", None), data["cell_methods"]
C:\Users\murk_\Documents\New folder\envs\my_xclim\lib\site-packages\xclim\core\cfchecks.py:43: UserWarning: Variable does not have a `standard_name` attribute.
  check_valid(vardata, "standard_name", data["standard_name"])
Traceback (most recent call last):

  File "C:\Users\murk_\Documents\New folder\envs\my_xclim\lib\site-packages\xarray\core\dataarray.py", line 731, in _getitem_coord
    var = self._coords[key]

KeyError: 'time'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\murk_\AppData\Local\Temp\ipykernel_9228\3547074178.py", line 1, in <module>
    csd=xc.indicators.atmos.cold_spell_days(T2)

  File "C:\Users\murk_\Documents\New folder\envs\my_xclim\lib\site-packages\xclim\core\indicator.py", line 791, in __call__
    outs = self.compute(**compute_das, **kwargs, **var_kwargs)

  File "<boltons.funcutils.FunctionBuilder-4>", line 2, in cold_spell_days

  File "C:\Users\murk_\Documents\New folder\envs\my_xclim\lib\site-packages\xclim\core\units.py", line 688, in wrapper
    out = func(*args, **kwargs)

  File "C:\Users\murk_\Documents\New folder\envs\my_xclim\lib\site-packages\xclim\indices\_threshold.py", line 161, in cold_spell_days
    group = over.resample(time=freq)

  File "C:\Users\murk_\Documents\New folder\envs\my_xclim\lib\site-packages\xarray\core\common.py", line 1151, in resample
    dim_coord = self[dim]

  File "C:\Users\murk_\Documents\New folder\envs\my_xclim\lib\site-packages\xarray\core\dataarray.py", line 742, in __getitem__
    return self._getitem_coord(key)

  File "C:\Users\murk_\Documents\New folder\envs\my_xclim\lib\site-packages\xarray\core\dataarray.py", line 735, in _getitem_coord
    self._coords, key, self._level_coords, dim_sizes

  File "C:\Users\murk_\Documents\New folder\envs\my_xclim\lib\site-packages\xarray\core\dataset.py", line 170, in _get_virtual_variable
    ref_var = variables[ref_name]

KeyError: 'time'
```

**Comment by Zeitsperre** [comment]
Hi there,

Just so we know the exact xclim version, could you return the output from the results from running:
```
import xclim
print(xclim.__version__)
```

For your problem, the issue might be here: 
```
DS= DS.rename({'XTIME':'Time'})
```
I think this field is case-sensitive, so try again but with `"time"`. Let us know if that fixes the problem or not!

**Comment by Murk89** [comment]
Hi, 

Thanks for getting back! The version is 0.32.1
I tried with DS= DS.rename({'XTIME':'Time'}), still the same error. 

The dims of DS.T2 are Time, south_north and west_east. I am wondering if the dim Time needs to be renamed to time?

**Comment by Murk89** [comment]
Well I tried with renaming the dim Time as time., however the same error persists.

**Comment by aulemahal** [comment]
Hi, it is a bit weird that when the dimension is named "time" the same error is raised. Could you provide us the output of `print(DS)`, if possible?

Also, just to be sure, I rewrote your example to what I think would work:
```python3
DS = xr.open_mfdataset("C:\\Users\\Public\\Documents\\Python files for plotting wrfoutput\\*.nc",concat_dim='Time', combine='nested', compat='no_conflicts', preprocess=None, engine=None, data_vars='all', coords='all', parallel=False, join='outer', attrs_file=None,)

DS = DS.rename(XTIME='time') # changed to lowercase
DS = DS.assign_coords(time=pd.to_datetime(DS['time'].values))  # changed to lowercase time here as well.

print(DS)

#try xclim index
T2=DS.T2
cs = xc.indicators.atmos.cold_spell_days(T2)
```

**Comment by Murk89** [comment]
Hi,
Tried the above steps, still the same error. XTIME does get renamed to time within the dataset, however doesn't show up as coordinates with DS.T2

Also I am wondering does the time have to be cf compliant? Because I know from some WRF pages that WRF time format might not exactly be cf compliant. Don't know if that has something to do with this error. 
print (DS) gives:

```
<xarray.Dataset>
Dimensions:                (Time: 8, south_north: 111, west_east: 114, bottom_top: 34, west_east_stag: 115, south_north_stag: 112, bottom_top_stag: 35, time: 8, soil_layers_stag: 4, seed_dim_stag: 2)
Coordinates:
 XLAT                   (Time, south_north, west_east) float32 dask.array<chunksize=(1, 111, 114), meta=np.ndarray>
  XLONG                  (Time, south_north, west_east) float32 dask.array<chunksize=(1, 111, 114), meta=np.ndarray>
 * time                   (time) datetime64[ns] 2090-11-02 ... 2090-11-09
    XLAT_U                 (Time, south_north, west_east_stag) float32 dask.array<chunksize=(1, 111, 115), meta=np.ndarray>
    XLONG_U                (Time, south_north, west_east_stag) float32 dask.array<chunksize=(1, 111, 115), meta=np.ndarray>
    XLAT_V                 (Time, south_north_stag, west_east) float32 dask.array<chunksize=(1, 112, 114), meta=np.ndarray>
    XLONG_V                (Time, south_north_stag, west_east) float32 dask.array<chunksize=(1, 112, 114), meta=np.ndarray>
Dimensions without coordinates: Time, south_north, west_east, bottom_top, west_east_stag, south_north_stag, bottom_top_stag, soil_layers_stag, seed_dim_stag
Data variables: (12/161)
    Times                  (Time) |S19 dask.array<chunksize=(1,), meta=np.ndarray>
    LU_INDEX               (Time, south_north, west_east) float32 dask.array<chunksize=(1, 111, 114), meta=np.ndarray>
    VAR_SSO                (Time, south_north, west_east) float32 dask.array<chunksize=(1, 111, 114), meta=np.ndarray>
    U                      (Time, bottom_top, south_north, west_east_stag) float32 dask.array<chunksize=(1, 34, 111, 115), meta=np.ndarray>
    V                      (Time, bottom_top, south_north_stag, west_east) float32 dask.array<chunksize=(1, 34, 112, 114), meta=np.ndarray>
    W                      (Time, bottom_top_stag, south_north, west_east) float32 dask.array<chunksize=(1, 35, 111, 114), meta=np.ndarray>
                    ...
    PCB                    (Time, south_north, west_east) float32 dask.array<chunksize=(1, 111, 114), meta=np.ndarray>
    PC                     (Time, south_north, west_east) float32 dask.array<chunksize=(1, 111, 114), meta=np.ndarray>
    LANDMASK               (Time, south_north, west_east) float32 dask.array<chunksize=(1, 111, 114), meta=np.ndarray>
    LAKEMASK               (Time, south_north, west_east) float32 dask.array<chunksize=(1, 111, 114), meta=np.ndarray>
    SST                    (Time, south_north, west_east) float32 dask.array<chunksize=(1, 111, 114), meta=np.ndarray>
    SST_INPUT              (Time, south_north, west_east) float32 dask.array<chunksize=(1, 111, 114), meta=np.ndarray>
Attributes: (12/129)
    TITLE:                            OUTPUT FROM WRF V4.1.3 MODEL
    START_DATE:                      2090-11-01_00:00:00
    SIMULATION_START_DATE:           2090-11-01_00:00:00
    WEST-EAST_GRID_DIMENSION:        115
    SOUTH-NORTH_GRID_DIMENSION:      112
    BOTTOM-TOP_GRID_DIMENSION:       35
                             ...
    ISLAKE:                          21
    ISICE:                           15
    ISURBAN:                         13
    ISOILWATER:                      14
    HYBRID_OPT:                      2
    ETAC:                            0.2
```
And DS.T2: 

```
<xarray.DataArray 'T2' (Time: 8, south_north: 111, west_east: 114)>
dask.array<concatenate, shape=(8, 111, 114), dtype=float32, chunksize=(1, 111, 114), chunktype=numpy.ndarray>
Coordinates:
    XLAT     (Time, south_north, west_east) float32 dask.array<chunksize=(1, 111, 114), meta=np.ndarray>
    XLONG    (Time, south_north, west_east) float32 dask.array<chunksize=(1, 111, 114), meta=np.ndarray>
Dimensions without coordinates: Time, south_north, west_east
Attributes:
    FieldType:    104
    MemoryOrder:  XY 
    description:  TEMP at 2 M
    units:        K
    stagger:      
```

**Comment by aulemahal** [comment]
Thanks for the printout!
Indeed, the "Time" dimension is different from the "XTIME" coordinate, I didn't realise that!

So for your use case, I'm pretty sure the following will solve it:
```python3
DS = xr.open_mfdataset("C:\\Users\\Public\\Documents\\Python files for plotting wrfoutput\\*.nc",concat_dim='Time', combine='nested', compat='no_conflicts', preprocess=None, engine=None, data_vars='all', coords='all', parallel=False, join='outer', attrs_file=None,)

DS = DS.rename(XTIME='time', Time='time') # changed to lowercase and named the dimension to match the coord
DS = DS.assign_coords(time=pd.to_datetime(DS['time'].values))  # changed to lowercase time here as well.

#try xclim index
T2=DS.T2
cs = xc.indicators.atmos.cold_spell_days(T2)
```

As for the CF-compliance, your issue actually triggered a discussion among the devs. xclim simply assumes the time dimension is named "time", But the CF convention are not that strict. The name could be anything, but if it has temporal units, then it is to be considered a time dimension. For the sake of code clarity and ease of maintenance, we made a choice to rely on a name, and it might not be that clear in the docs.

**Comment by Murk89** [comment]
Hi, 
Many thanks for all the help. The above suggestions have worked. Just a typo in the second line may be. 
```
DS = DS.rename({'XTIME':'time', 'Time':'time'}) 
```
Instead of 
```
DS = DS.rename(XTIME='time', Time='time')
```
Now I am stuck with plotting the results at every grid point. 
I tried with the plotting code that usually works with xarrays
```
import matplotlib
cs.plot() 
AttributeError: 'NoneType' object has no attribute 'matplotlib

cs.cold_spell_days.plot()
AttributeError: 'DataArray' object has no attribute 'cold_spell_days'

```

**Comment by Murk89** [comment]
Thanks for getting back. 
So I tried applying the cold_spell_frequency to another WRF dataset which is a daily output spanning six months i.e. 01-11-2090 to 30-04-2091 ; a timeseries comprising 181 days. And for each grid box of my domain I need the number of events which count as a cold spell in the given time period.
I am trying to understand the format/idea of the index's results here. Why is the time dim 181? Does that mean that all 181 days were part of a cold spell? My understanding was that the index would return the frequency, as in the sum of the cold spell events. So for example for a given grid box, for the selected time period, there are going to be 10 cold spell events. Is my understanding of the index correct? This is the array I get as a result of the applied index:

```
<xarray.DataArray 'cold_spell_frequency' (time: 181, south_north: 111, west_east: 114)>
dask.array<where, shape=(181, 111, 114), dtype=float64, chunksize=(1, 111, 114), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) datetime64[ns] 2090-11-01 2090-11-02 ... 2091-04-30
Dimensions without coordinates: south_north, west_east
Attributes:
    units:          
    cell_methods:   
    history:        [2022-01-25 10:24:52] cold_spell_frequency: COLD_SPELL_FR...
    standard_name:  cold_spell_frequency
    long_name:      Number of cold spell events
    description:    D number cold spell events, defined as 5 or more consecut...
```

**Comment by aulemahal** [comment]
This result is not what you expected I think. Seeing how the "description" field was edited, I believe you passed `freq='D'` to  `atmos.cold_spell_days`? The `freq` argument controls the resampling _of the output_, and indeed here the function returns the count of cold spells within such a period. Your data starts on the first of november and ends at the end of april, I think a good frequency to use would be `AS-NOV` (yearly starting in november) or `2QS-NOV` (every 2 quarters (so biannually), starting in november). Those strings are from pandas (https://pandas.pydata.org/docs/user_guide/timeseries.html#dateoffset-objects).
You could also choose a smaller period (ex: MS, monthly) and then sum over, but in the case of spells this is a bit dangerous because spells that go across a period a cut in half and if that makes them too short, they are not counted.

However, the first one might be simpler to understand, but you'll encounter another feature of xclim that might work against you : masking of incomplete periods. As the year is not complete, xclim will put NaNs. You're best guess here is to change the method of handling NaNs temporarily:

```python3
with xc.set_options(check_missing='skip'):
    cs = xc.atmos.cold_spell_frequency(T2, freq='AS-NOV')
```
This is explained in the docs, here : https://xclim.readthedocs.io/en/stable/checks.html#missing-values-identification
and here : https://xclim.readthedocs.io/en/stable/notebooks/customize.html#Missing-values

**Comment by Murk89** [comment]
Hi, 
Your explanation is so helpful. Many thanks. My understanding about the ```freq``` argument was that it is related to the input data. 
So I used 
```
 with xc.set_options(check_missing='skip'):
        cs = xc.atmos.cold_spell_frequency(T2, freq='AS-NOV')
```
as this looks the most suitable one. And now I have the following resultant array:

```
<xarray.DataArray 'cold_spell_frequency' (time: 1, south_north: 111, west_east: 114)>
dask.array<where, shape=(1, 111, 114), dtype=float64, chunksize=(1, 74, 74), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) datetime64[ns] 2090-11-01
Dimensions without coordinates: south_north, west_east
Attributes:
    units:          
    cell_methods:   
    history:        [2022-01-25 15:14:01] cold_spell_frequency: COLD_SPELL_FR...
    standard_name:  cold_spell_frequency
    long_name:      Number of cold spell events
    description:    Annual number cold spell events, defined as 5 or more con..

```
And then ``` cs.plot() ```  gives the plot I required. 
![image](https://user-images.githubusercontent.com/59877746/151010930-c9e5ec8f-49e4-4694-9bd6-6cf41215f7d9.png)

And also to note if with ``` xc.set_options(check_missing='skip') ``` is not used, then a blank plot is returned. 
![image](https://user-images.githubusercontent.com/59877746/151011370-3140d1f6-c1d1-4807-9674-ea4e92cf028c.png)
So was very useful to know that. 
Many many thanks.
